# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KhS2WUZ7SSmM7LQlG6pwzArCHpYKXl_x

**Reading csv file using pandas**
"""

import pandas as pd
import os

def getFilePath(filename):
  currentDir  = os.getcwd()
  fullPath = os.path.join(currentDir, filename)
  return fullPath

df = pd.read_csv(getFilePath('police.csv'))
print(df.head(5))

"""Using pandas “head()” function to display the top 5 rows from our data set.

**Last 5 rows of the data set**
"""

df.tail(5)

"""**Dimension of the Data set and information about dataset**"""

df.shape
df.info()

#missing values in columns
df.isnull().sum()

df.describe()

df.sample(5)

"""**loc() and iloc() methods are used in slicing data from the pandas DataFrame**"""

df.loc[:5,['driver_age','violation']]

df.loc[(df.driver_age <16)& (df.violation == 'Speeding')]

df.iloc[:5,:5]

"""**We can sort our DataFrame by index or values with Pandas “sort_index()” and “sort_values()” functions**"""

df[['stop_date','driver_age','driver_race','violation','stop_outcome']].sort_values(by='driver_age')

"""**We can use the Pandas query() function to filter our data frame as per our conditions**"""

df.query('45<driver_age <50').head()

"""**Filtering based on the condition**"""

male_drivers = df[df['driver_gender'] == 'M']
print("\nMale drivers:")
print(male_drivers.head())

# Example 2: Filter rows where 'violation' is 'Speeding' and 'is_arrested' is True
speeding_arrests = df[(df['violation'] == 'Speeding') & (df['is_arrested'] == True)]
print("\nSpeeding violations resulting in arrest:")
print(speeding_arrests.head())

"""**missing values**"""

# Example: Count missing values in each column
missing_values = df.isnull().sum()
print("\nMissing values in each column:")
print(missing_values)

# Example: Fill missing values in 'county_name' with a default value
df['county_name'].fillna('Unknown', inplace=True)

"""**calculating summary statics**"""

# Calculate mean age of drivers
mean_age = df['driver_age'].mean()
print(f"\nMean age of drivers: {mean_age}")

# Example: Calculate count of each unique value in 'stop_outcome'
outcome_counts = df['stop_outcome'].value_counts()
print("\nStop outcomes count:")
print(outcome_counts)